#!/usr/bin/env bash
# Web servers are the unique part of software generatior of HTML pages, let’s install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
